apiVersion: v1
kind: Namespace
metadata:
  name: aic-infrastructure
  labels:
    name: aic-infrastructure
    environment: production
    platform: 002aic
    tier: infrastructure
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: infrastructure-resource-quota
  namespace: aic-infrastructure
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "15"
    services.loadbalancers: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: infrastructure-limit-range
  namespace: aic-infrastructure
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container
