# Infrastructure Services Database secrets
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-database-secret
  namespace: aic-infrastructure
type: Opaque
data:
  # Base64 encoded database URLs
  notification-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9ub3RpZmljYXRpb25fZGI=
  audit-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9hdWRpdF9kYg==
  security-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9zZWN1cml0eV9kYg==
  backup-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9iYWNrdXBfZGI=
  caching-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9jYWNoaW5nX2Ri
  queue-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9xdWV1ZV9kYg==
  logging-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9sb2dnaW5nX2Ri
  feature-flag-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9mZWF0dXJlX2ZsYWdfZGI=
  metrics-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9tZXRyaWNzX2Ri
  model-registry-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9tb2RlbF9yZWdpc3RyeV9kYg==
  event-streaming-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9ldmVudF9zdHJlYW1pbmdfZGI=
  recommendation-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9yZWNvbW1lbmRhdGlvbl9kYg==
  content-management-db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZS5haWMtcGxhdGZvcm06NTQzMi9jb250ZW50X21hbmFnZW1lbnRfZGI=
---
# Infrastructure Services Redis secret
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-redis-secret
  namespace: aic-infrastructure
type: Opaque
data:
  url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlLmFpYy1wbGF0Zm9ybTo2Mzc5
  l1-url: cmVkaXM6Ly9yZWRpcy1sMXNlcnZpY2UuYWljLWluZnJhc3RydWN0dXJlOjYzNzk=
  l2-url: cmVkaXM6Ly9yZWRpcy1sMnNlcnZpY2UuYWljLWluZnJhc3RydWN0dXJlOjYzNzk=
---
# Notification service secrets
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-notification-secret
  namespace: aic-infrastructure
type: Opaque
data:
  smtp-host: c210cC5nbWFpbC5jb20=
  smtp-username: bm90aWZpY2F0aW9uc0BhcHBsaWVkaW5ub3ZhdGlvbmNvcnAuY29t
  smtp-password: c210cF9wYXNzd29yZA==
  sendgrid-api-key: U0cuZXhhbXBsZV9zZW5kZ3JpZF9hcGlfa2V5
  twilio-account-sid: QUNleGFtcGxlX3R3aWxpb19hY2NvdW50X3NpZA==
  twilio-auth-token: ZXhhbXBsZV90d2lsaW9fYXV0aF90b2tlbg==
---
# Security service secrets
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-security-secret
  namespace: aic-infrastructure
type: Opaque
data:
  vault-token: aHZzLmV4YW1wbGVfdmF1bHRfdG9rZW4=
  encryption-key: c3VwZXJfc2VjdXJlX2VuY3J5cHRpb25fa2V5XzI1Ng==
---
# Backup service secrets
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-backup-secret
  namespace: aic-infrastructure
type: Opaque
data:
  s3-access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  s3-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  s3-bucket: MDAyYWljLWJhY2t1cC1idWNrZXQ=
  encryption-key: YmFja3VwX2VuY3J5cHRpb25fa2V5XzI1Ng==
---
# Storage secrets
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-storage-secret
  namespace: aic-infrastructure
type: Opaque
data:
  s3-access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  s3-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  s3-bucket: MDAyYWljLWluZnJhc3RydWN0dXJlLXN0b3JhZ2U=
