apiVersion: v1
kind: Namespace
metadata:
  name: aic-business
  labels:
    name: aic-business
    environment: production
    platform: 002aic
    tier: business
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: business-resource-quota
  namespace: aic-business
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: business-limit-range
  namespace: aic-business
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container
