# Integration service secrets
apiVersion: v1
kind: Secret
metadata:
  name: business-integration-secret
  namespace: aic-business
type: Opaque
data:
  # Zapier credentials
  zapier-api-key: emFwaWVyX2V4YW1wbGVfYXBpX2tleQ==
  # Salesforce credentials
  salesforce-client-id: M01WeDEyM2V4YW1wbGVfc2FsZXNmb3JjZV9jbGllbnRfaWQ=
  salesforce-client-secret: c2FsZXNmb3JjZV9leGFtcGxlX2NsaWVudF9zZWNyZXQ=
  salesforce-username: dXNlckBleGFtcGxlLnNhbGVzZm9yY2UuY29t
  salesforce-password: c2FsZXNmb3JjZV9wYXNzd29yZA==
  # HubSpot credentials
  hubspot-api-key: aHVic3BvdF9leGFtcGxlX2FwaV9rZXk=
  hubspot-client-id: aHVic3BvdF9leGFtcGxlX2NsaWVudF9pZA==
  hubspot-client-secret: aHVic3BvdF9leGFtcGxlX2NsaWVudF9zZWNyZXQ=
  # Slack credentials
  slack-bot-token: eG94Yi1leGFtcGxlLXNsYWNrLWJvdC10b2tlbg==
  slack-app-token: eGFwcC1leGFtcGxlLXNsYWNrLWFwcC10b2tlbg==
  # Microsoft Teams credentials
  teams-client-id: bXNfdGVhbXNfZXhhbXBsZV9jbGllbnRfaWQ=
  teams-client-secret: bXNfdGVhbXNfZXhhbXBsZV9jbGllbnRfc2VjcmV0
  # Google Workspace credentials
  google-client-id: Z29vZ2xlX2V4YW1wbGVfY2xpZW50X2lk
  google-client-secret: Z29vZ2xlX2V4YW1wbGVfY2xpZW50X3NlY3JldA==
---
# Support service secrets
apiVersion: v1
kind: Secret
metadata:
  name: business-support-secret
  namespace: aic-business
type: Opaque
data:
  # Zendesk credentials
  zendesk-api-token: emVuZGVza19leGFtcGxlX2FwaV90b2tlbg==
  zendesk-email: c3VwcG9ydEBleGFtcGxlLmNvbQ==
  zendesk-subdomain: ZXhhbXBsZWNvbXBhbnk=
  # Intercom credentials
  intercom-access-token: aW50ZXJjb21fZXhhbXBsZV9hY2Nlc3NfdG9rZW4=
  intercom-app-id: aW50ZXJjb21fZXhhbXBsZV9hcHBfaWQ=
  # OpenAI credentials for AI support
  openai-api-key: c2stZXhhbXBsZV9vcGVuYWlfYXBpX2tleQ==
  # Freshdesk credentials (alternative)
  freshdesk-api-key: ZnJlc2hkZXNrX2V4YW1wbGVfYXBpX2tleQ==
  freshdesk-domain: ZXhhbXBsZWNvbXBhbnkuZnJlc2hkZXNrLmNvbQ==
