apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-tls
  namespace: observability
spec:
  dnsNames:
    - otel-collector
  secretName: otel-collector-tls
  commonName: otel-collector
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
