apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: aic-platform
  labels:
    app: auth-service
    tier: core
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        tier: core
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: auth-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: auth-service
        image: 002aic/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: auth-db-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt-secret
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: aic-platform
  labels:
    app: auth-service
    tier: core
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: auth-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: aic-platform
  labels:
    app: auth-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: aic-platform
data:
  config.yaml: |
    server:
      port: 8080
      timeout: 30s
    auth:
      jwt_expiry: 24h
      refresh_expiry: 168h
      bcrypt_cost: 12
    rate_limiting:
      enabled: true
      requests_per_minute: 100
    logging:
      level: info
      format: json
