apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-service
  namespace: aic-ai-ml
  labels:
    app: model-training-service
    tier: ai-ml
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: model-training-service
  template:
    metadata:
      labels:
        app: model-training-service
        tier: ai-ml
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: model-training-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: model-training-service
        image: 002aic/model-training-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-ml-database-secret
              key: training-db-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ai-ml-redis-secret
              key: url
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service.aic-ai-ml.svc.cluster.local:5000"
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: model-storage
          mountPath: /app/models
        - name: data-storage
          mountPath: /app/data
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: config
        configMap:
          name: model-training-service-config
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-training-pvc
      - name: data-storage
        persistentVolumeClaim:
          claimName: training-data-pvc
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      nodeSelector:
        accelerator: nvidia-tesla-gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: model-training-service
  namespace: aic-ai-ml
  labels:
    app: model-training-service
    tier: ai-ml
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: model-training-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-training-service
  namespace: aic-ai-ml
  labels:
    app: model-training-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-training-pvc
  namespace: aic-ai-ml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-data-pvc
  namespace: aic-ai-ml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-training-service-config
  namespace: aic-ai-ml
data:
  config.yaml: |
    server:
      port: 8080
      timeout: 300s
    training:
      max_concurrent_jobs: 3
      job_timeout: 7200s
      checkpoint_interval: 600s
      auto_scaling: true
    frameworks:
      tensorflow:
        enabled: true
        version: "2.13"
      pytorch:
        enabled: true
        version: "2.0"
      scikit_learn:
        enabled: true
        version: "1.3"
    storage:
      model_path: "/app/models"
      data_path: "/app/data"
      checkpoint_path: "/app/checkpoints"
    logging:
      level: info
      format: json
