apiVersion: v1
kind: Namespace
metadata:
  name: aic-ai-ml
  labels:
    name: aic-ai-ml
    environment: production
    platform: 002aic
    tier: ai-ml
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-ml-resource-quota
  namespace: aic-ai-ml
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    requests.nvidia.com/gpu: "4"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-ml-limit-range
  namespace: aic-ai-ml
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
