apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: "http://vault.vault.svc:8200"
    path: "pki/sign/otel-collector"
    auth:
      tokenSecretRef:
        namespace: cert-manager
        name: vault-token
        key: token
