apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: registry.example.com/ai-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP
              value: "{{ .Values.kafka.bootstrap }}"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
