global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Kong metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Keycloak metrics
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Authorization Service metrics
  - job_name: 'authorization-service'
    static_configs:
      - targets: ['authorization-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis metrics (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']

  # PostgreSQL metrics (if postgres_exporter is added)
  # - job_name: 'postgresql'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']
