apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.example.internal"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          role: external-secrets
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
