apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-service
  template:
    metadata:
      labels:
        app: infra-service
    spec:
      containers:
        - name: infra-service
          image: registry.example.com/infra-service:latest
          ports:
            - containerPort: 9100
          env:
            - name: KAFKA_BOOTSTRAP
              value: "{{ .Values.kafka.bootstrap }}"
---
apiVersion: v1
kind: Service
metadata:
  name: infra-service
spec:
  selector:
    app: infra-service
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
