apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
type: Opaque
stringData:
  POSTGRES_URL: {{ default "postgres://postgres:postgres@postgres:5432/postgres" .Values.postgres.url | quote }}
