apiVersion: v2
name: nexus-platform
description: Nexus AI-Native PaaS Platform - Production Helm Chart
type: application
version: 2.0.0
appVersion: "2.0.0"
home: https://github.com/thomas-carter-aic/002AIC
sources:
  - https://github.com/thomas-carter-aic/002AIC
maintainers:
  - name: Nexus Platform Team
    email: platform@appliedinnovationcorp.com
keywords:
  - ai
  - ml
  - paas
  - platform
  - kubernetes
  - microservices
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mongodb
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: kafka
    version: 22.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
