[tool.poetry]
name = "nexus-sdk-py"
version = "0.1.0"
description = "Python SDK for AIC Nexus"
authors = ["Your Name <you@example.com>"]
packages = [{include = "sdk"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31"

[tool.poetry.dev-dependencies]
pytest = "^8.0"
