apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      containers:
        - name: workspace-service
          image: registry.example.com/workspace-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BOOTSTRAP
              value: "{{ .Values.kafka.bootstrap }}"
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
spec:
  selector:
    app: workspace-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
