apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-clusternamespace
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200" # change to your vault address
      path: "secret/data"
      version: "v2"
      auth:
        token:
          secretRef:
            name: vault-token
            namespace: external-secrets
            key: token
