apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workspace-secrets
  namespace: workspace
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-clusternamespace
    kind: ClusterSecretStore
  target:
    name: workspace-secrets
    creationPolicy: Owner
  dataFrom:
    - key: secret/data/platform/workspace
