apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault
  annotations:
    # Replace with the IRSA role ARN returned by Terraform
    eks.amazonaws.com/role-arn: "{{ .Values.vault.irsaRoleArn }}"
