apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            tls_settings:
              cert_file: /conf/tls/tls.crt
              key_file: /conf/tls/tls.key
              client_ca_file: /conf/tls/ca.crt
          http:
    processors:
      batch:
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: "jaeger-collector.observability.svc:14250"
      prometheusremotewrite:
        endpoint: "http://prometheus-operated.observability.svc:9090/api/v1/write"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
