apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-kuma-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/002AIC  # Update with your repo URL
    targetRevision: HEAD
    path: infra/helm/kong
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: kong.env.admin_gui_url
          value: "https://admin.002aic.local"
        - name: kong.env.admin_api_uri
          value: "https://admin.002aic.local"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-configuration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/002AIC  # Update with your repo URL
    targetRevision: HEAD
    path: infra/k8s
    directory:
      include: "kong-*.yaml"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma-mesh-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-org/002AIC  # Update with your repo URL
    targetRevision: HEAD
    path: infra/k8s
    directory:
      include: "kuma-*.yaml"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
