name: Build, Scan & Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.example.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push images
        run: |
          ./scripts/build-and-load-images.sh dev-cluster registry.example.com
      - name: Trivy scan images
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: registry.example.com/workspace-service:latest
