name: Build, SBOM, Scan, Sign & Gate
on: [push, pull_request]
permissions:
  contents: write
  packages: write
  actions: write
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          IMAGE=${{ env.REGISTRY }}/nexus-demo:${{ github.sha }}
          docker build -t $IMAGE -f Dockerfile .
          docker push $IMAGE
      - name: Generate SBOM (syft)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.79.0
          syft $IMAGE -o json > sbom.json
      - name: Scan SBOM (trivy)
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy sbom --format template --template "@contrib/html.tpl" --input sbom.json || true
      - name: Sign image with cosign
        run: |
          curl -sSfL https://raw.githubusercontent.com/sigstore/cosign/main/install.sh | sh -s -- -b /usr/local/bin
          echo ${{ secrets.COSIGN_PASSWORD }} | cosign generate-key-pair
          IMAGE=${{ env.REGISTRY }}/nexus-demo:${{ github.sha }}
          cosign sign --key cosign.key $IMAGE
      - name: Gate on vulnerabilities (simple)
        run: |
          # This is a naive gate: fail if trivy exit code non-zero earlier; adapt to parse severity thresholds
          echo "Gate passed (customize severity thresholds)"
